#!/usr/bin/env bash
# -*- mode:sh -*-
# Required apps:
# 1. spotify-tui

playing="▶"

case $1 in
    play)
        if [[ $(spt pb -sf %s ) == *$playing* ]]
        then
            echo is playing
            exit 0
        fi
        spt pb -t
        ;;
    stop)
        if [[ $(spt pb -sf %s ) == *$playing* ]]
        then
            echo is playing
            spt pb -t
        fi
        ;;
    pause)
        if [[ $(spt pb -sf %s ) == *$playing* ]]
        then
            echo is playing
            spt pb -t
        fi
        ;;
    next)
        spt pb -n
        ;;
    prev)
        spt pb -p
        ;;
    up)
        vol=$(spt vol -sf %v)
        if [[ $vol -lt 100 ]]
        then
            spt pb -v $((vol+5))
        fi
        ;;
    down)
        vol=$(spt vol -sf %v)
        if [[ $vol -gt 0 ]]
        then
            spt pb -v $((vol-5))
        fi
        ;;
    *)
        echo "Usage: $0 {play|stop|restart|pause|next|prev}"
        exit 1
        ;;
esac
