#!/bin/bash

# Remove the telnet:// and change the colon before the port
# number to a space.
TELNET_STRING=$(echo $1 | awk -F'/' '{print $3}' | awk -F':' '{print $1 " " $2}' )

gnome-terminal -e "telnet $TELNET_STRING"
